#!/usr/bin/env bash
# Bash script that will display information about subdomains
domain () {
	display_info() {
    subdomain=$1
    domain=$2
    result=$(dig $subdomain.$domain +short)
    record_type=$(dig $subdomain.$domain | awk '/ANSWER SECTION/ {getline; print $4}')
    echo "The subdomain $subdomain is a $record_type record and points to $result"
}

# Check if both domain and subdomain parameters are provided
if [ $# -eq 2 ]; then
    display_info $2 $1
else
    # If only domain parameter is provided, display information for default subdomains
    display_info "www" $1
    display_info "lb-01" $1
    display_info "web-01" $1
    display_info "web-02" $1
fi
}
domain "$1" "$2"
