#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting
# to another page.
sudo apt-get update -y
sudo apt-get install -y nginx

echo "301 Moved Permanently" > /var/www/html/index.nginx-debian.html
sudo sed -i "/location 193 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default

sudo service nginx restart
